// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHtF1NkONsSkUd2t9owV99pd4DbXcAfDw',
    appId: '1:947772237646:web:d8250ac7336a4a0d40e01f',
    messagingSenderId: '947772237646',
    projectId: 'tiktok-flutter-6adf4',
    authDomain: 'tiktok-flutter-6adf4.firebaseapp.com',
    storageBucket: 'tiktok-flutter-6adf4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb_7GkPBNcVDKTG7yorR6ddof5fAcPAP4',
    appId: '1:947772237646:android:d6e32ade8257b39640e01f',
    messagingSenderId: '947772237646',
    projectId: 'tiktok-flutter-6adf4',
    storageBucket: 'tiktok-flutter-6adf4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhySR6ttFYrogRZlv0A6x1XKDJeMMwdhU',
    appId: '1:947772237646:ios:74dfbafb0a8c893940e01f',
    messagingSenderId: '947772237646',
    projectId: 'tiktok-flutter-6adf4',
    storageBucket: 'tiktok-flutter-6adf4.appspot.com',
    iosClientId: '947772237646-ccbmk4so73b1r1u49jak8mkdio9gnig5.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokTutorial',
  );
}
